name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "andrespontt@gmail.com"
        git config --global user.name "andrespontt"
        git remote set-url origin https://db41c67fbd0896c21a283354bfdc8d75f9c30d19@github.com/andrespontt/andrespontt.github.io.git
        npm run deploy